dist: xenial
language: python
sudo: false
stages:
  - name: after_success
    if: branch = master
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
before_install:
  - "virtualenv fossa-env && fossa-env/bin/pip install poetry==0.12.14"
  - "fossa-env/bin/poetry install --no-dev"
  - "fossa-env/bin/pip freeze > requirements.txt"
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
  - "fossa analyze"
  - "rm -rf fossa-env requirements.txt"
install:
  - "pip install tox-travis==0.12 poetry==0.12.14"
script:
  - "tox"
after_success:
  - "pip install coverage==4.5.3 codacy-coverage==1.3.11"
  - "coverage xml"
  - "python-codacy-coverage -r coverage.xml"
